apiVersion: v1
kind: ConfigMap
metadata:
  name: coat-config
  namespace: {{ include "coat.namespace" . }}
  labels:
    {{- include "coat.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ tpl (toString $value) $ | quote }}
  {{- end }}
