[package]
name = "coat-validator"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
coat-domain = { path = "../domain" }
coat-observability = { path = "../observability" }
anyhow.workspace = true
axum.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
