{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: jattg-agent-secrets
  namespace: {{ include "jattg.namespace" . }}
  labels:
    {{- include "jattg.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.values }}
  {{ $key }}: {{ tpl (toString $value) $ | quote }}
  {{- end }}
{{- end }}
